{{--
    Shared email footer: "{lead} {attribution}." The attribution is the
    configured developer name (linked when a URL is set), or "Sentinel for
    Statamic" when branding is off. Both values are escaped before markup.

    Vars: $lead - e.g. "This report was generated by"
--}}
@php
    $_devName = $sentinelDevName ?? null;
    $_devUrl  = $sentinelDevUrl ?? null;
    $sentinelFooterAttribution = $_devName
        ? ($_devUrl
            ? '<a href="' . e($_devUrl) . '" style="color:#64748b; text-decoration:underline;">' . e($_devName) . '</a>'
            : e($_devName))
        : 'Sentinel for Statamic';
@endphp
<div style="background:#f8fafc; border-top:1px solid #e2e8f0; padding:20px 32px;">
    <div style="font-size:12px; color:#64748b;">
        {{ $lead }} {!! $sentinelFooterAttribution !!}.
    </div>
</div>
